experiment:
  name: PI-IAM4VP

# Toggle between IAM4VP and PI-IAM4VP with the use_physics param
model:
  type: PI-IAM4VP
  params: {}

data:
  dataset_version: v3
  cut: [[36, 68], [125, 189]]
  include_target: false
  lead_time: 1
  interval: 1
  muti_target_steps: 1
  start_time_x: 0
  end_time_x: 5
  start_time_y: 6
  end_time_y: 11
  num_workers: 8
  train:
    start_time: "2000-01-01 00:00:00"
    end_time: "2003-12-25 00:00:00"
    batch_size: 16
    shuffle: true
  val:
    start_time: "2004-01-01 00:00:00"
    end_time: "2004-12-25 00:00:00"
    batch_size: 16
    shuffle: false

training:
  litmodel: mutiout_imvp_small_world
  lr: 5e-4
  eta_min: 0.0
  max_epoch: 20
  loss_type: MAE
  early_stopping_patience: 5
  extra_kwargs:
    muti_out_nums: 6
    time_prediction: 6

trainer:
  precision: 32
  log_every_n_steps: 5
  static_graph: true

logging:
  checkpoint_base: /home/ebugaev/checkpoints/
  comet_api_key: ""
  comet_project: WeatherPredictions
  log_code_file: null
