experiment:
  name: PredFormerGFT-USA

model:
  type: PredFormerGFT
  params:
    height: 32
    width: 64
    num_channels: 69
    pre_seq: 12
    after_seq: 12
    patch_size: 8
    dim: 256
    heads: 6
    dim_head: 32
    dropout: 0.0
    attn_dropout: 0.0
    drop_path: 0.0
    scale_dim: 4
    depth: 2
    Ndepth: 18
    path_to_constants: /home/fratnikov/weather_bench/1.40625deg/constants/constants_1.40625deg.nc
    cut: [[75, 107], [164, 228]]

data:
  dataset_version: v3
  cut: [[75, 107], [164, 228]]
  include_target: false
  lead_time: 1
  interval: 1
  muti_target_steps: 1
  start_time_x: 0
  end_time_x: 11
  start_time_y: 12
  end_time_y: 23
  num_workers: 4
  pin_memory: true
  train:
    start_time: "2000-01-01 00:00:00"
    end_time: "2000-02-15 00:00:00"
    batch_size: 4
    shuffle: true
  val:
    start_time: "2000-02-16 00:00:00"
    end_time: "2000-02-25 00:00:00"
    batch_size: 4
    shuffle: false

training:
  litmodel: mutiout_f
  lr: 1.0e-4
  eta_min: 0.0
  max_epoch: 1
  loss_type: MAE
  early_stopping_patience: 5
  extra_kwargs:
    muti_out_nums: 6

trainer:
  precision: 32
  log_every_n_steps: 5
  static_graph: true
  num_sanity_val_steps: 0
  float32_matmul_precision: high

logging:
  checkpoint_base: /home/fa.buzaev/WeatherPredictions/checkpoints/
  comet_project: WeatherPredictions
  log_code_file: null
