experiment:
  name: WeatherGFT

model:
  type: WeatherGFT
  params:
    hidden_dim: 256
    physics_part_coef: 0.1
    encoder_layers: [2, 2, 2]
    edcoder_heads: [2, 4, 4]
    encoder_scaling_factors: [0.5, 0.5, 1]
    encoder_dim_factors: [-1, 2, 2]
    body_layers: [2, 2, 2, 2, 2, 2]
    body_heads: [6, 6, 6, 6, 6, 6]
    body_scaling_factors: [1, 1, 1, 1, 1, 1]
    body_dim_factors: [1, 1, 1, 1, 1, 1]
    decoder_layers: [2, 2, 2]
    decoder_heads: [4, 4, 2]
    decoder_scaling_factors: [1, 2, 1]
    decoder_dim_factors: [1, 0.5, 1]
    channels: 69
    head_dim: 128
    window_size: [4, 8]
    relative_pos_embedding: false
    out_kernel: [2, 2]
    pde_block_depth: 3
    block_dt: 300
    inverse_time: false
    use_checkpoint: true

data:
  dataset_version: v1
  include_target: false
  lead_time: 1
  interval: 1
  num_workers: 4
  train:
    start_time: "2000-01-01 00:00:00"
    end_time: "2003-12-25 00:00:00"
    muti_target_steps: 6
    batch_size: 16
    shuffle: true
  val:
    start_time: "2004-01-01 00:00:00"
    end_time: "2004-12-25 00:00:00"
    muti_target_steps: 12
    batch_size: 16
    shuffle: false

training:
  litmodel: multiout_double
  lr: 1e-4
  eta_min: 0.0
  max_epoch: 15
  loss_type: MAE
  early_stopping_patience: 5
  extra_kwargs:
    muti_out_nums: 6

trainer:
  precision: 32
  log_every_n_steps: 5
  static_graph: true

logging:
  checkpoint_base: /home/fa.buzaev/WeatherPredictions/checkpoints/
  comet_project: WeatherPredictions
  log_code_file: null
